# Fundamental concepts of tensors using tensorflow

We're going to conver:
1. intro to tensors
2. getting info from tensors
3. manipulating tensors
4. tensors and numpy
5. using @tf.function(a way to speed up your regular python function)
6. using gpu with tensorflow(or tpu)
7. exercises yourself!!

# Introduction to tensors

In [125]:
# Import Tensorflow
import tensorflow as tf

# Checking the version of tensoflow
print(tf.__version__)

2.9.2


In [126]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [127]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [128]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [129]:
# Check the dimension of our vector
vector.ndim

1

In [130]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [131]:
matrix.ndim

2

In [132]:
# Create another matrix
another_matrix = tf.constant([[10.7,8.4],
                              [3.,4.],
                              [5.,8.]], dtype = tf.float16) # specify the data type with dtype parameter
another_matrix                                              # by default it shows as float32 for floating numbers
                                                            # 32 and 16 are precision numbers lower the number easier or less memory to store the tensors in our computer

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.7,  8.4],
       [ 3. ,  4. ],
       [ 5. ,  8. ]], dtype=float16)>

In [133]:
# ndim for another matrix 
another_matrix.ndim

2

In [134]:
# total no of dimensions is the no of elements in the shape

In [135]:
# let's create a tensor
tensor = tf.constant(
    [[[1,2,3],
      [4,5,6]],
     [[7,8,9],
      [10,11,12]],
     [[13,14,15],
      [15,16,17]]]
)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [15, 16, 17]]], dtype=int32)>

In [136]:
tensor.ndim

3

In [137]:
sample_tensor = tf.constant([1,2,3,4],dtype = tf.int16)
sample_tensor

<tf.Tensor: shape=(4,), dtype=int16, numpy=array([1, 2, 3, 4], dtype=int16)>

To Create a tensor:

* tf.constant() is used
* the data can be of any type eg: int...
there are 16 and 32 bit precision for the datatype based on the number the memory allocation of the tensor is done lower the number less memory for allocation.
* by default precision would be 32
* we can manually change the precision by
while creating a tensor eg:tensor = tf.constant([1,2,3],dtype = int16) it overrides the default precision and sets it as 16 bit precision 

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (eg: wind speed and direction)
* Matrix: a dimensional array of numbers
* Tensor: an n-dimensional array of number(when n can be any number eg:0,1,2,3...)
* ndim = no of elements in the shape of the tensor
* shape tells us the how many dimensions are there and how many elements are there

### Creating tensors with tf.variable

In [138]:
# create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [139]:
# let's try to change one of the elements in our changeable tensor
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

* we can access each elements of a tensor by accessing their index positions

In [140]:
changeable_tensor[0] = 7

TypeError: ignored

In [ ]:
# how about we try .assign()
changeable_tensor[0].assign(7)

In [ ]:
# let's try to change our unchangeable tensor
unchangeable_tensor[0]

In [ ]:
unchangeable_tensor[0] = 7

In [ ]:
unchangeable_tensor[0].assign(7)

* tf.variable lets you to change the elements of the tensor 
* tf.constant is a constant tensor we can't change the elements in the tensor
* we can access the each elements by accessing their index position

## Creating Random Tensors

* random tensors are tensors of some abitrary size which contain random numbers.
* There are many ways to create a random tensor eg.normal, uniform... but the distribution of these no varies.
* when a nueral network starts to learn it starts with the random tensors. After learning for sometime it updates its representation(patterns, features, weights)

#### Normal Distribution
outputs the numbers from normal distribution

In [ ]:
# Create two random (but the same) tensors 
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility (same as randomseed from numpy)
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 =random_2.normal(shape = (3,2))
random_1, random_2, random_1 == random_2

#### Uniform Distribution
outputs numbers from uniform distribution

In [ ]:
uniform_distribution = tf.random.Generator.from_seed(42)
uniform_distribution = uniform_distribution.uniform(shape = (3,2))
uniform_distribution  # tf.random.uniform(seed = 42, shape = (3,2)) another way to create a random tensor

### Shuffle the order of elements in a tensor
this is used to shuffle the dataset so that the model can learn diff types of data

In [ ]:
# shuffle the tensors 
random_tensor = tf.random.uniform(seed = 42, shape = (3,2))
random_tensor

In [ ]:
tf.random.shuffle(random_tensor)

In [ ]:
tf.random.shuffle(random_tensor, seed = 42) # it won' produce the same results

In [ ]:
# produces same results
tf.random.set_seed(42) # global seed
tf.random.shuffle(random_tensor, seed = 42) # operation-level seeds

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

* If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
* If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
* If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
* If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

inshorter:
* global seed is used when we want to reproduce same results in shuffle
* operation seed is used when we want to reproduce same results in picking random sequence
* operation and global seed can also be used in picking a random sequence
* when operation seed alone used in shuffling the result gets varied

### Other ways to make tensors

In [ ]:
# create a tensor of all ones
tf.ones([10, 7])

In [ ]:
# create a tensor of all zeroes
tf.zeros(shape = (10,7)) # we can also use shape parameter

### creating tensors from numpy arrays

In [ ]:
import numpy as np
numpy_a = np.arange(1,25, dtype = np.int32)
numpy_a

In [ ]:
a = tf.constant(numpy_a)
b = tf.constant(numpy_a, shape = (3,8)) # shape must match the total no of elements
a, b

In [ ]:
tf.ones(shape = (10,10))

what we covered:
* there are many ways to create tensors but there is also builtin method in tf to create tensor
* tf.zeros creates a tensor with zeroes with the given shape
* we can also create tensors from numpy array by passing those into tf.constant we can create tensors
* we can manualy change the shape of the tensors when passing the numpy arrays
* numpy arrays and tensorflow tensors will look like same but tensorflow tensor will able to run faster in gpu

## Getting information from tensors
these attributes are used when we are dealing with large tensors
* shape 
* rank(no of dimensions)
* axis or dimension (indexing)
* size

In [ ]:
sample_tensor = tf.zeros(shape = (2,3,4,5))
sample_tensor

In [ ]:
# get various attributes of our tensor
print("datatype of every element:", sample_tensor.dtype)
print("number of dimensions (rank):", sample_tensor.ndim)
print("shape of tensor:", sample_tensor.shape)
print("elements along the 0 the axis:", sample_tensor.shape[0])
print("total number of elements in our tensor:", tf.size(sample_tensor))

# to print just the number
print("total number of elements in our tensor:", tf.size(sample_tensor).numpy())

### Indexing tensors 
tensors can be indexed just like python lists
* python lists are 1 dimension so we use only [:1] 
* but the tensors have more dimension so we have to apply to each and every one of them if we need to

In [ ]:
sample_tensor[:2,:2,:2,:2]

In [141]:
# get the first element from each dimension from each index except for the final one
sample_tensor[:1,:1,:1,:]

InvalidArgumentError: ignored

In [ ]:
# we can [:] this if we want to print the whole thing using slicing

In [ ]:
sample_tensor_2 = tf.constant([[1,2],
                               [3,4]])
sample_tensor_2,sample_tensor_2[-1]

In [ ]:
# add in extra dimension to our tensor
sample_tensor_3 = sample_tensor_2[..., tf.newaxis] # adds the new axis at the end
sample_tensor_3                                    # (...) copies the current dimension and adds an extra dimension

In [ ]:
# alternative to tf.newaxis
tf.expand_dims(sample_tensor_2,axis = -1)

# axis specifies where you would want to expand the dimension
# if 0 is specified new axis will be added in the begining

## manipulating tensors(tensor operations)
* manipulating tensors with the basic operations is a little bit slower in gpu
* using tensor builtin method for manipulating tensors are lot better in gpu
* these are element vise operations (ie) go to one element at a time

In [ ]:
# you can change the values of a tensor using basic operators
tensor = tf.ones(shape = (2,2))
tensor

In [ ]:
tensor+10

In [142]:
tensor * 10

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]],

       [[130, 140, 150],
        [150, 160, 170]]], dtype=int32)>

In [143]:
tensor - 10

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[-9, -8, -7],
        [-6, -5, -4]],

       [[-3, -2, -1],
        [ 0,  1,  2]],

       [[ 3,  4,  5],
        [ 5,  6,  7]]], dtype=int32)>

In [144]:
tensor/9

<tf.Tensor: shape=(3, 2, 3), dtype=float64, numpy=
array([[[0.11111111, 0.22222222, 0.33333333],
        [0.44444444, 0.55555556, 0.66666667]],

       [[0.77777778, 0.88888889, 1.        ],
        [1.11111111, 1.22222222, 1.33333333]],

       [[1.44444444, 1.55555556, 1.66666667],
        [1.66666667, 1.77777778, 1.88888889]]])>

In [145]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]],

       [[130, 140, 150],
        [150, 160, 170]]], dtype=int32)>

In [146]:
tf.add(tensor,200)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[201, 202, 203],
        [204, 205, 206]],

       [[207, 208, 209],
        [210, 211, 212]],

       [[213, 214, 215],
        [215, 216, 217]]], dtype=int32)>

## matrix multiplication

2 rules for matrix multiplication

1. the inner dimensions must match
2. the resulting matrix has the shape of the outer matrix

In [147]:
# matrix multiplication in tensorflow
print(tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [15 16 17]]], shape=(3, 2, 3), dtype=int32)


In [148]:
tensor = tf.constant([[10,7],
                     [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [149]:
# we can remove the middle part in the function
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [150]:
# it's an element wise multiplication
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [151]:
# matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [152]:
tensor.shape

TensorShape([2, 2])

In [153]:
# create a tensor (3,2)
tensor2 = tf.constant([[1,2,3],
                       [4,5,6]])
tensor2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [154]:
tensor3 = tf.constant([[1,2],
                       [2,4],
                       [5,4]])
tensor3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 4],
       [5, 4]], dtype=int32)>

In [155]:
tensor2 @ tensor3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 22],
       [44, 52]], dtype=int32)>

In [156]:
tf.matmul(tensor2, tensor3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 22],
       [44, 52]], dtype=int32)>

In [157]:
tf.matmul(tensor3, tensor3)

InvalidArgumentError: ignored

In [ ]:
tensor3 

In [158]:
# changing the shape of the tensor(shuffles the no and changes the shape based on our requirement)
tensor_3 = tf.reshape(tensor3,shape = (2,3))
tensor_3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 2],
       [4, 5, 4]], dtype=int32)>

In [159]:
tensor3 @ tensor_3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 10],
       [18, 24, 20],
       [21, 30, 26]], dtype=int32)>

In [160]:
tensor3.shape, tensor_3.shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [161]:
tf.matmul(tensor3,tensor_3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 10],
       [18, 24, 20],
       [21, 30, 26]], dtype=int32)>

In [162]:
# transpose matrix(transposes axis)
tf.transpose (tensor3),tensor3

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [2, 4, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 4],
        [5, 4]], dtype=int32)>)

In [163]:
# try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(tensor3),tensor3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 30],
       [30, 36]], dtype=int32)>

## dot product
matrix multiplication is also referred to as the dot product.

you can perform matrimultiplication using:
1. tf.matmul
2. tensor @ tensor@
3. tf.tensordot()

In [164]:
# perform the dot product on tensor3
tf.tensordot(tf.transpose(tensor3),tensor3,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 30],
       [30, 36]], dtype=int32)>

In [165]:
tf.matmul(tensor3,tf.reshape(tensor3,shape = (2,3)) )

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 10],
       [18, 24, 20],
       [21, 30, 26]], dtype=int32)>

In [166]:
tf.matmul(tf.reshape(tensor3,shape = (2,3)),tensor3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 18],
       [34, 44]], dtype=int32)>

In [167]:
tf.matmul(tf.transpose(tensor3),tensor3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 30],
       [30, 36]], dtype=int32)>

In [168]:
tensor3 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 4],
       [5, 4]], dtype=int32)>

In [169]:
tf.transpose(tensor3)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [2, 4, 4]], dtype=int32)>

In [170]:
tf.reshape(tensor3,shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 2],
       [4, 5, 4]], dtype=int32)>

In [171]:
tf.__version__

'2.9.2'

### changing the datatype of a tensor
default is 32 bit precision
* 16 bit precision is a lot faster

In [172]:
# create a new tensor with default datatype
B = tf.constant([1.4,5.6])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.4, 5.6], dtype=float32)>

In [173]:
B.dtype

tf.float32

In [174]:
C = tf.constant([1,2])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [175]:
C.dtype

tf.int32

In [176]:
# change the float32 to float16 (reduced precision)
B = tf.cast(B,dtype = tf.float16)
B.dtype

tf.float16

In [177]:
C = tf.cast(C,dtype = tf.int16)
C.dtype

tf.int16

In [178]:
# change from int16 to float16
E = tf.cast(C,dtype = tf.float16)
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>,
 tf.float16)

### aggregating tensors

condensing them from multiple values down to a smaller amount of values

In [179]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [180]:
# get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [181]:
# create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([83, 60, 56, 36, 84, 85, 39, 91, 47, 60, 61, 67, 83, 19, 10, 44,  6,
        8, 97,  6, 10, 33, 85, 53, 63, 82, 32, 79, 23, 78, 88, 86, 35, 84,
       81, 64, 74, 38,  0, 77, 69, 87, 75, 36, 32, 92, 99, 90, 94, 57])>

In [182]:
tf.size(E), E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [183]:
# find the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [184]:
# find the maximum 
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [185]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=58>

In [186]:
# sum of the tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2938>

In [187]:
# find the variance of our tensor, we need access to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=813>

In [188]:
# find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.517757>

* if we get input must be real or complex error then we should convert our dtype to float

In [189]:
# find the variance of our tensor(for other methods we may not need to use math but for variance and stddev we must use math)
tf.math.reduce_variance(tf.cast(E,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=813.26245>

* representation outputs are prediction probabilities

### find the positional maximum and minimum

In [190]:
# create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [191]:
# find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [192]:
F[42]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [193]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [194]:
# find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [195]:
# check of equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [196]:
# find the position min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [197]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [198]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### squeezing a tensor(removing all single dimensions)
squeeze is used when there is a lot of single dimension in your tensor and you need to remove that dimension

In [199]:
# create a tensor to get  started 
G = tf.constant(tf.random.uniform(shape = [50]),shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [200]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [201]:
G_squeeze = tf.squeeze(G)
G_squeeze,G_squeeze.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>, TensorShape([50]))

### one hot encoding 
* if we receive any value error then we should probably change the datatype of the input from int to float
* most builtin fucntions requries us to pass the inputs as float type
* we can't send strings to the neural networks we should convert to numbers that's why one hot encoding is used 
* it bascially creates an array with the help of somelist

In [202]:
# create a list of indices
some_list = [0,1,2,3] # could be red, green, blue, purple

# one hot encode our list of indices
tf.one_hot(some_list,depth = 4) # here length of the list and depth (ie) 4 * 4
                                # here depth represents how many elements should be added per array

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [203]:
# changing the datatype of the one hot encoder
tf.cast(tf.one_hot(some_list, depth = 4),dtype = tf.int32)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)>

In [204]:
# setting a values to the encoder
tf.one_hot(some_list,depth = 4, on_value="it's not over", off_value = "it's over")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"it's not over", b"it's over", b"it's over", b"it's over"],
       [b"it's over", b"it's not over", b"it's over", b"it's over"],
       [b"it's over", b"it's over", b"it's not over", b"it's over"],
       [b"it's over", b"it's over", b"it's over", b"it's not over"]],
      dtype=object)>

In [205]:
### squaring, log, sqroot
B = tf.range(1,10)
B

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [206]:
tf.square(B)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [207]:
# find the squareroot
tf.math.sqrt(tf.cast(B,dtype = tf.float32)) # requires float32 datatype for squareroot

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [208]:
tf.math.log(tf.cast(B,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### tensors and numpy
tensorflow interacts beautifully with numpy arrays

In [209]:
# create a tensor directly from a numpy array
J = tf.constant(np.array([1.4,5.5]))
J

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1.4, 5.5])>

In [210]:
# convert our tensor back to numpy array
np.array(J),type(np.array(J))

(array([1.4, 5.5]), numpy.ndarray)

In [211]:
# another way to convert our tensor to numpy
J.numpy(),type(J.numpy())

(array([1.4, 5.5]), numpy.ndarray)

In [212]:
# the default types of each are different
numpy_j = tf.constant(np.array([4.5]))
tensor_j = tf.constant([5.5])

# check the datatypes of each
numpy_j, tensor_j

(<tf.Tensor: shape=(1,), dtype=float64, numpy=array([4.5])>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([5.5], dtype=float32)>)

* the datatype might be different when we comparing between numpy and tensor

### finding access to gpu

In [213]:
# returns a list of physical devices available
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [214]:
!nvidia-smi

Wed Dec  7 14:59:49 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   77C    P0    33W /  70W |    314MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------